server:
  port: 8081
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#Spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: "group_id"
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    bootstrap-servers: ip_here
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.example.kafka'